### ISSUE TITLE
Добавить недостающие флаги

### ISSUE THREAD

**Issue by syros** [AdmiralDS/flags#4]
1. Ниуэ
2. Северные Марианские Острова
3. Реюньон
4. Сен-Бартелеми
5. Сен-Мартен
6. Сент-Пьер и Микелон
7. Синт-Мартен (Нидерландская Часть)
8. Малые Тихоокеанские Отдаленные Острова Соединенных Штатов
9. Виргинские Острова, Сша
10. Абхазия

**Comment by DrUNE** [comment]
- [ ] [https://github.com/AdmiralDS/icons/issues/21](https://github.com/AdmiralDS/icons/issues/21)
